/**
 * convention.md 5.3 — 에러 코드 문자열은 이 파일 한 곳의 상수로 관리한다.
 * 서버 enum(backend/architecture.md 7.5)과 이름을 일치시킨다.
 * 추가 시 spec/api/<화면>-api.md의 에러 코드 표와 대조한다.
 */
export const ERROR_CODES = {
  // auth-api.md 5장
  AUTH_PROVIDER_TOKEN_INVALID: 'AUTH_PROVIDER_TOKEN_INVALID',
  AUTH_PROVIDER_UNAVAILABLE: 'AUTH_PROVIDER_UNAVAILABLE',
  AUTH_SIGNUP_TOKEN_EXPIRED: 'AUTH_SIGNUP_TOKEN_EXPIRED',
  CONSENT_REQUIRED: 'CONSENT_REQUIRED',
  CONSENT_VERSION_STALE: 'CONSENT_VERSION_STALE',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_REUSED: 'AUTH_REFRESH_TOKEN_REUSED',
  WITHDRAWAL_CONFIRM_REQUIRED: 'WITHDRAWAL_CONFIRM_REQUIRED',
  WITHDRAWAL_SUBSCRIPTION_EXPIRY_NOT_AGREED: 'WITHDRAWAL_SUBSCRIPTION_EXPIRY_NOT_AGREED',
  WITHDRAWAL_ARCHIVE_IDENTITY_MISSING: 'WITHDRAWAL_ARCHIVE_IDENTITY_MISSING',
  EMAIL_FORMAT_INVALID: 'EMAIL_FORMAT_INVALID',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  EMAIL_VERIFICATION_RESEND_COOLDOWN: 'EMAIL_VERIFICATION_RESEND_COOLDOWN',
  EMAIL_VERIFICATION_SEND_LIMIT: 'EMAIL_VERIFICATION_SEND_LIMIT',
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
  EMAIL_VERIFICATION_CODE_MISMATCH: 'EMAIL_VERIFICATION_CODE_MISMATCH',
  EMAIL_VERIFICATION_CODE_EXPIRED: 'EMAIL_VERIFICATION_CODE_EXPIRED',
  EMAIL_VERIFICATION_ATTEMPTS_EXCEEDED: 'EMAIL_VERIFICATION_ATTEMPTS_EXCEEDED',
  EMAIL_VERIFICATION_NOT_FOUND: 'EMAIL_VERIFICATION_NOT_FOUND',

  // onboarding-api.md 5장
  ONBOARDING_INTEREST_REQUIRED: 'ONBOARDING_INTEREST_REQUIRED',
  ONBOARDING_INTEREST_LIMIT_EXCEEDED: 'ONBOARDING_INTEREST_LIMIT_EXCEEDED',
  ONBOARDING_TOPIC_UNAVAILABLE: 'ONBOARDING_TOPIC_UNAVAILABLE',
  ONBOARDING_INTERESTS_NOT_SET: 'ONBOARDING_INTERESTS_NOT_SET',
  ONBOARDING_NOT_COMPLETED: 'ONBOARDING_NOT_COMPLETED',
  ONBOARDING_ALREADY_COMPLETED: 'ONBOARDING_ALREADY_COMPLETED',

  // library-api.md 5장
  LIBRARY_CURSOR_INVALID: 'LIBRARY_CURSOR_INVALID',
  LIBRARY_ITEM_NOT_FOUND: 'LIBRARY_ITEM_NOT_FOUND',
  LIBRARY_COMPLETION_NOT_REACHED: 'LIBRARY_COMPLETION_NOT_REACHED',
  /** 무료 티어 한도 소진 → 페이월. PLAY_LIMIT_REACHED(유료 한도 안내)와 화면이 다르다 */
  PLAY_LIMIT_EXCEEDED: 'PLAY_LIMIT_EXCEEDED',
  PLAY_LIMIT_REACHED: 'PLAY_LIMIT_REACHED',

  // 공용 코드(common-error-handling.md 4.1)
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  CONTENT_NOT_FOUND: 'CONTENT_NOT_FOUND',
  CONTENT_WITHDRAWN: 'CONTENT_WITHDRAWN',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // 클라이언트 전용 — 서버 응답이 없는 실패의 정규화(common-error-handling.md)
  NETWORK_ERROR: 'NETWORK_ERROR',
  TIMEOUT: 'TIMEOUT',
  UNKNOWN: 'UNKNOWN',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
