/**
 * architecture.md 7.5 — 모든 에러 코드는 이 enum 한 곳에서 관리한다.
 * 문자열 리터럴을 직접 던지지 않는다.
 *
 * 도메인 코드를 추가·변경하면 해당 API 명세와
 * `docs/features/common-error-handling.md` 6장 표를 함께 갱신한다.
 */
export enum ErrorCode {
  // --- 기반 코드 (도메인 무관) ---
  /** 예상하지 못한 5xx. 내부 사유를 노출하지 않기 위해 항상 이 코드로 고정한다 */
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  /** 요청 형식·검증 실패 (400) */
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  /** 인증 없음·만료 (401) */
  UNAUTHORIZED = 'UNAUTHORIZED',
  /** 권한 없음 (403) */
  FORBIDDEN = 'FORBIDDEN',
  /** 리소스 없음 (404) */
  NOT_FOUND = 'NOT_FOUND',
  /** 상태 충돌 (409) */
  CONFLICT = 'CONFLICT',
  /** 레이트 리밋 (429) */
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  /** 외부 연동 실패 — AI 서버·스토어·스토리지 */
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',

  // --- 인증·계정 (auth-api.md 5장) ---
  AUTH_PROVIDER_TOKEN_INVALID = 'AUTH_PROVIDER_TOKEN_INVALID',
  AUTH_PROVIDER_UNAVAILABLE = 'AUTH_PROVIDER_UNAVAILABLE',
  AUTH_SIGNUP_TOKEN_EXPIRED = 'AUTH_SIGNUP_TOKEN_EXPIRED',
  CONSENT_REQUIRED = 'CONSENT_REQUIRED',
  CONSENT_VERSION_STALE = 'CONSENT_VERSION_STALE',
  AUTH_REFRESH_TOKEN_INVALID = 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_REUSED = 'AUTH_REFRESH_TOKEN_REUSED',

  // --- 회원 탈퇴 ---
  WITHDRAWAL_CONFIRM_REQUIRED = 'WITHDRAWAL_CONFIRM_REQUIRED',
  WITHDRAWAL_SUBSCRIPTION_EXPIRY_NOT_AGREED = 'WITHDRAWAL_SUBSCRIPTION_EXPIRY_NOT_AGREED',
  WITHDRAWAL_ARCHIVE_IDENTITY_MISSING = 'WITHDRAWAL_ARCHIVE_IDENTITY_MISSING',

  // --- 이메일 인증 ---
  EMAIL_FORMAT_INVALID = 'EMAIL_FORMAT_INVALID',
  EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
  EMAIL_VERIFICATION_RESEND_COOLDOWN = 'EMAIL_VERIFICATION_RESEND_COOLDOWN',
  EMAIL_VERIFICATION_SEND_LIMIT = 'EMAIL_VERIFICATION_SEND_LIMIT',
  EMAIL_SEND_FAILED = 'EMAIL_SEND_FAILED',
  EMAIL_VERIFICATION_CODE_MISMATCH = 'EMAIL_VERIFICATION_CODE_MISMATCH',
  EMAIL_VERIFICATION_CODE_EXPIRED = 'EMAIL_VERIFICATION_CODE_EXPIRED',
  EMAIL_VERIFICATION_ATTEMPTS_EXCEEDED = 'EMAIL_VERIFICATION_ATTEMPTS_EXCEEDED',
  EMAIL_VERIFICATION_NOT_FOUND = 'EMAIL_VERIFICATION_NOT_FOUND',

  // --- 온보딩 (onboarding-api.md 5장) ---
  /** 1단계는 건너뛸 수 없다 — `topic_ids`가 비었음 */
  ONBOARDING_INTEREST_REQUIRED = 'ONBOARDING_INTEREST_REQUIRED',
  /** 관심 주제 상한(3개) 초과. 초과분을 잘라내지 않고 거부한다 (onboarding-api.md 4.3) */
  ONBOARDING_INTEREST_LIMIT_EXCEEDED = 'ONBOARDING_INTEREST_LIMIT_EXCEEDED',
  /**
   * 존재하지 않거나 `is_visible = false`인 주제.
   * **두 경우를 구분하지 않는다** — 구분하면 임의 UUID로 비노출 주제의 존재를 탐침할 수 있다.
   */
  ONBOARDING_TOPIC_UNAVAILABLE = 'ONBOARDING_TOPIC_UNAVAILABLE',
  /** 1단계를 마치지 않은 계정의 호출. 클라이언트는 1단계로 되돌린다 */
  ONBOARDING_INTERESTS_NOT_SET = 'ONBOARDING_INTERESTS_NOT_SET',
  /** 완료 요청 전에 첫 드립 상태를 조회함. 대기는 완료 이후에만 존재한다 */
  ONBOARDING_NOT_COMPLETED = 'ONBOARDING_NOT_COMPLETED',
  /** 완료된 계정의 온보딩 API 호출. 클라이언트는 라이브러리로 진입한다 */
  ONBOARDING_ALREADY_COMPLETED = 'ONBOARDING_ALREADY_COMPLETED',

  // --- 콘텐츠 (공용 — common-error-handling.md 4.1) ---
  /** 담기 등에서 **건별 결과**로도 전달된다 (onboarding-api.md 4.6 `failed[]`) */
  CONTENT_NOT_FOUND = 'CONTENT_NOT_FOUND',
  /** 회수·만료된 콘텐츠 (`status != published`) */
  CONTENT_WITHDRAWN = 'CONTENT_WITHDRAWN',
}
