/**
 * architecture.md 7.5 — 모든 에러 코드는 이 enum 한 곳에서 관리한다.
 * 문자열 리터럴을 직접 던지지 않는다.
 *
 * 도메인 코드를 추가·변경하면 해당 API 명세와
 * `docs/pages/common-error-handling.md` 6장 표를 함께 갱신한다.
 */
export enum ErrorCode {
  // --- 기반 코드 (도메인 무관) ---
  /** 예상하지 못한 5xx. 내부 사유를 노출하지 않기 위해 항상 이 코드로 고정한다 */
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  /** 요청 형식·검증 실패 (400) */
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  /** 인증 없음·만료 (401) */
  UNAUTHORIZED = 'UNAUTHORIZED',
  /** 권한 없음 (403) */
  FORBIDDEN = 'FORBIDDEN',
  /** 리소스 없음 (404) */
  NOT_FOUND = 'NOT_FOUND',
  /** 상태 충돌 (409) */
  CONFLICT = 'CONFLICT',
  /** 레이트 리밋 (429) */
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  /** 외부 연동 실패 — AI 서버·스토어·스토리지 */
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',

  // --- 인증·계정 (auth-api.md 5장) ---
  AUTH_PROVIDER_TOKEN_INVALID = 'AUTH_PROVIDER_TOKEN_INVALID',
  AUTH_PROVIDER_UNAVAILABLE = 'AUTH_PROVIDER_UNAVAILABLE',
  AUTH_SIGNUP_TOKEN_EXPIRED = 'AUTH_SIGNUP_TOKEN_EXPIRED',
  CONSENT_REQUIRED = 'CONSENT_REQUIRED',
  CONSENT_VERSION_STALE = 'CONSENT_VERSION_STALE',
  AUTH_REFRESH_TOKEN_INVALID = 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_REUSED = 'AUTH_REFRESH_TOKEN_REUSED',

  // --- 회원 탈퇴 ---
  WITHDRAWAL_CONFIRM_REQUIRED = 'WITHDRAWAL_CONFIRM_REQUIRED',
  WITHDRAWAL_SUBSCRIPTION_EXPIRY_NOT_AGREED = 'WITHDRAWAL_SUBSCRIPTION_EXPIRY_NOT_AGREED',
  WITHDRAWAL_ARCHIVE_IDENTITY_MISSING = 'WITHDRAWAL_ARCHIVE_IDENTITY_MISSING',

  // --- 이메일 인증 ---
  EMAIL_FORMAT_INVALID = 'EMAIL_FORMAT_INVALID',
  EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
  EMAIL_VERIFICATION_RESEND_COOLDOWN = 'EMAIL_VERIFICATION_RESEND_COOLDOWN',
  EMAIL_VERIFICATION_SEND_LIMIT = 'EMAIL_VERIFICATION_SEND_LIMIT',
  EMAIL_SEND_FAILED = 'EMAIL_SEND_FAILED',
  EMAIL_VERIFICATION_CODE_MISMATCH = 'EMAIL_VERIFICATION_CODE_MISMATCH',
  EMAIL_VERIFICATION_CODE_EXPIRED = 'EMAIL_VERIFICATION_CODE_EXPIRED',
  EMAIL_VERIFICATION_ATTEMPTS_EXCEEDED = 'EMAIL_VERIFICATION_ATTEMPTS_EXCEEDED',
  EMAIL_VERIFICATION_NOT_FOUND = 'EMAIL_VERIFICATION_NOT_FOUND',
}
